name: Test for rules_steep

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
    
    - name: Test all by bazel
      run: bazelisk test //...
